<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="1"
            tests="1">

  <testsuite name="refactor"
    errors="1" failures="1" hostname="" id="" package="refactor" skipped="3"
    tests="1" time="21.52" timestamp="">
  
    <testcase name="check addition" classname="refactor" time="21.52" assertions="1">  <failure message="Timed out while waiting for element &lt;#cwos&gt; to be present for 2000 milliseconds. - expected [0;32m&#34;found&#34;[0m but got: [0;31m&#34;not found&#34;[0m [0;90m(2018ms)[0m">    at Object.check addition (/Users/admin/qadevmtn/practice-automation/tests/refactor.js:59:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)</failure>

    
      <failure message="    at Object.check addition (/Users/admin/qadevmtn/practice-automation/tests/refactor.js:59:14)">    at processTicksAndRejections (internal/process/task_queues.js:97:5)</failure>
      <error message="Timed out while waiting for element &lt;#cwos&gt; to be present for 2000 milliseconds. - expected [0;32m&#34;found&#34;[0m but got: [0;31m&#34;not found&#34;[0m [0;90m(2018ms)[0m" type="error">    at processTicksAndRejections (internal/process/task_queues.js:97:5)</error>
    
    </testcase>
  

  
    <system-err>
      [0;31m  TimeoutError: An error occurred while running .setValue() command on &lt;input[type=&#34;text&#34;]&gt;: 
   {&#34;status&#34;:-1,&#34;state&#34;:&#34;&#34;,&#34;value&#34;:null,&#34;errorStatus&#34;:&#34;&#34;,&#34;error&#34;:&#34;An unknown error has occurred.&#34;}[0m
[0;90m       at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
    </system-err>
  

  
    
    <testcase
      name="check subtraction" classname="refactor">
      <skipped />
    </testcase>
    
    <testcase
      name="check division" classname="refactor">
      <skipped />
    </testcase>
    
    <testcase
      name="check multiplication" classname="refactor">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
